language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install: nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: t7+NfxLMeJ+Ma6UVZEaEvlJZRGisqoc6L74T6tYfNxJyHnFzHQwCdIqaY1XAvoTtK4hKOztcHid3RAWblD5I/iHtmNAbkDCxqVZMNi0kuUXf02w0DQ/vW3WGlHpKV4ZoCIGYMVTFk2BCaLxUGD1xmHwL8s1OadKzIYaa+l9FMIh5TAAF6xEP9fOV/LGI6h0bdMyCIa3r4pS/+sSsqQnRMJHBs4r86WmvKMFmeI/oIYCL5KtuDDH5BBvhWn22AK2xw3GdMTjzZdvP5h76kiXXk4bbepN9PJOX1NGrTghoT+pwTcjJBqtoIz2m+rnVp4yK0x3R4dXz3YHRlMPgEqlh4yuIVKcDZtOelJkLfPLrSjjG31FWwZ5vZwgDzVLpUIJfA/VTkuW8j0BqhARWGHMyt6VY9BsAoSqZb5hAps4JpdatQDEJeYmQHYTLEA6ETWsnMW/cHpCW3rdiz7Fig/wG4IIuGeifpusqakws3YQQSzyoT+8NAdqPABTMTRIo3e6VrR2HDm44bu+EwSkdwb7TFPuqiAsl52gEhvr9F/Cl+oJrNI6z+WqLUxNnRifeSFv91TZJ5CviBrGDIP70N9K0ZjZiQaPU/feCRO83dD/1WH/Hiy/EW0RyxpXibn7BYh1uvm6CUpTsl78K2SmaaUSSd2WaBox4ECqwkyLBk9bgBlc=
  app: arcane-scrubland-46989
  on:
    repo: Level-turing-team/level_front_end
    branch: main
  skip_cleanup: 'true'
