language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install: nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Q4tMgI/qUWHoiQ++dvzFJgujRfLsNUr1nRodBRgtShv7bq3PoRYg5MliejAnXV5uKJYBZl8sewwJ98XUmzgpl7z3YEn0mDiq56Gh57cPzxwQMLiix8eEgM5O6gRCnDOA403JzBuFChJXXD9q5r7aq2fm5bwcxM+m60REe1I0phI1NrxushVFmiMQvK8fBYIPSuseJClWpD4yuWVd28GxuTnomuzC5CvQ/B9PF76SNTIaWRnI7D2cr14LCyYnSXiYrIz8XIDBIOjloaLWq9Sb7eEB5wmLqVRQUamJy4OKm/XJ69YJuYe7pjr6ZcHql6Jfp3tRMWWJcSqBgb94xW+7OaEXZ9VE5a0SG/teAffqovOOP7wCV+7LaCqMMU0ySDaoaPJnKY5fRw3RUbj+Fa4bpIVZeTTSht0xzPOhsRULnHbLfETsh9oD6J7eQnASy72ob1JRVlWXcywP+zOXiojh56+w/S4mfqCKv/ZxE5BR4I5xfo926ftFStIAxEwrIDGCOdpK3QvPjVW9dVQJPwc2Z3TgY/lq42/xXhEZPNGCKN1uG550h+V1glClI5fXvTYqW83eN/ZDh+j5oFwyXWGGTP7OaVfTT4N1LxA7QaYEP7M+wJD2MGyzpUkYPCrbgFTb7arX83kfcUNsVz0NZ4dnlw2BURGNbbJg0Q5E5qR7J2M=
  app: arcane-scrubland-46989
  on:
    repo: Level-turing-team/level_front_end
    branch: main
  skip_cleanup: 'true'
